[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"
time = { version = "0.3.44", features = ["local-offset"] }

uuid = { version = "1.18.1", features = ["v7", "v4"] }
